source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SAWebPlayer_Example', :exclusive => true do
  pod 'SAWebPlayer', :path => '../'
end

target 'SAWebPlayer_Tests', :exclusive => true do
  pod 'SAWebPlayer', :path => '../'

  
end
