source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'SAWebPlayer_Example' do
  pod 'SAWebPlayer', :path => '../'
  
  target 'Tests' do
      inherit! :search_paths
  end
end

